name: portfolio
description: A simple portfolio about myself after working 5 months in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^3.0.1 #font
  flutter_svg: ^1.1.1+1 #svg
  flutter_riverpod: ^1.0.4 #state management
  flutter_staggered_grid_view: 0.6.2 #staggedGrid
  url_launcher: ^6.1.5 #URLauncher
  scroll_to_index: ^3.0.1 #scrollToIndex
  http: ^0.13.5 #httpclient

dev_dependencies:
  flutter_test:
    sdk: flutter


  #flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/

  fonts:
    - family: sfmono
      fonts:
        - asset: fonts/sfmono.otf
